### ISSUE TITLE
`index_of_coincidence` has discrepant results with www.dcode.fr/index-coincidence

### ISSUE THREAD

**Issue by jakewilliami** [Smaug123/ClassicalCiphers.jl#32]
E.g., 
```julia
julia> ClassicalCiphers.index_of_coincidence("""
       To be, or not to be, that is the question—
       Whether 'tis Nobler in the mind to suffer
       The Slings and Arrows of outrageous Fortune,
       Or to take Arms against a Sea of troubles,
       And by opposing end them?
       William Shakespeare - Hamlet
       """)
1.5006420133538778
```
But dcode.fr reports the IoC as 0.06773.
```julia
julia> index_of_coincidence("smaug123classicalciphers")
0.6190476190476191
```
But decode.fr reports the IoC as 0.06667.

**Comment by jakewilliami** [comment]
The above commit fixes this discrepancy.  But the question is: are dcode.fr correct?...

**Comment by Smaug123** [comment]
So as far as I can see, the difference is that I assume the alphabet is `'a'..'z'`, whereas the new one assumes the alphabet is precisely `delete_duplicates(input_string)` (for the obvious interpretation of what that notation means). I think `new` can't be right, for that reason: we know the string "AAAAAA" is extremely strange because it's drawn from `A..Z`, but if it were drawn from a language with only one character then it would be a perfectly ordinary string.

Does that sound reasonable?

**Comment by jakewilliami** [comment]
Ahh, I see!  That's reasonable, yes.  Closing now!
